wasmCloud/capability-providers

Makefile.common
fs/Makefile
http-client/Makefile
http-server/Makefile
logging/Makefile
nats/Makefile
redis-streams/Makefile
redis/Makefile
redisgraph/Makefile
s3/Makefile
telnet/Makefile

The common Makefile had an error that resulted in `cross build ...` not getting called.

Fix Makefile build targets

---

http-server/Cargo.toml
http-server/src/lib.rs
nats/Cargo.toml
nats/src/generated/core.rs
nats/src/lib.rs
redis/Cargo.toml
redis/src/lib.rs

0.15.x requires that all capability providers:
* Gracefully ignore attempts at binding actors that are already bound
* Support returning a health status in response to a health check

Idempotent configuration binding and support for health checks

---

.github/workflows/fs-release.yml
.github/workflows/fs.yml
.github/workflows/httpclient-release.yml
.github/workflows/httpclient.yml
.github/workflows/httpserver-release.yml
.github/workflows/httpserver.yml
.github/workflows/logging-release.yml
.github/workflows/logging.yml
.github/workflows/redis-release.yml
.github/workflows/redis.yml
.github/workflows/redisgraph-release.yml
.github/workflows/redisgraph.yml
.github/workflows/redisstreams-release.yml
.github/workflows/redisstreams.yml
.github/workflows/s3-release.yml
.github/workflows/s3.yml
.github/workflows/telnet-release.yml
.github/workflows/telnet.yml

Fixes #16
All of these additions here are copy/pasted from the TEMPLATEs in the `.github/workflows` directory, so it's all the same code coming in. Each individual build action (the `provider.yml`s) build and test the provider when a file has been modified in that specific provider. This saves a _lot_ of time, especially when we are working on capability providers individually. The release action (`provider-release.yml`) will build, test, and release the provider to `crates.io` and a parJEEzy to our wasmcloud azure registry for distribution. This action is kicked off by pushing a tag to the main branch with the form of `provider-vX.Y.Z`, for example `redisgraph-v0.9.2`. After merging this PR, I will tag an initial release for each provider.

Automated build & release actions for individual providers

---

s3/Cargo.toml
s3/src/lib.rs
s3/src/s3.rs

Related to #12 
This updates the S3 provider to 0.15 compliance and using the `wasmcloud:blobstore` contract ID and actor interface.
I've confirmed that the previous test suite runs & passes, I've also included a `docker run` oneliner for future tests of this project because it took me a few minutes to track down the exact Minio server flags that I needed.

Update S3 to 0.15 compliance and blobstore actor interface

---

fs/Cargo.toml
fs/README.md
fs/src/lib.rs

Updated FS provider to use `wasmCloud` terminology and the `blobstore` actor interface for its shared types.
Tests are passing alongside the `actor-interface` doctest. The badges in the README will likely be corrupted for the time being until we get this provider published onto crates.io.
Related to #12

FS provider 0.15

---

logging/Cargo.toml
logging/README.md
logging/src/lib.rs

PR incoming with all other providers updated to use interface versions.
This logging provider has been tested and verified to log messages that are logged in an actor, both using `write_log` directly and using log macros (e.g. `error!`, `info!`).

Updated logging provider to 0.15 compliance and interface versions

---

fs/Cargo.toml
fs/src/lib.rs
http-server/Cargo.toml
http-server/src/lib.rs
nats-kvcache/Cargo.toml
nats-kvcache/src/lib.rs
nats-kvcache/tests/integration.rs
redis/Cargo.toml
redis/src/kvredis.rs
redis/src/lib.rs
redisgraph/Cargo.toml
redisgraph/examples/sample-graph-actor/Cargo.toml
redisgraph/examples/sample-graph-actor/src/lib.rs
redisgraph/src/conversions.rs
redisgraph/src/lib.rs
redisgraph/src/rgraph.rs
s3/Cargo.toml
s3/src/lib.rs
s3/src/s3.rs

This will allow us to re-release our capability providers, including a release to crates.io where they can be imported as libraries.

Updating 0.15 providers to actor interface pinned versions

---

http-client/Cargo.toml
http-client/README.md
http-client/src/http_client.rs
http-client/src/lib.rs

- Updated to use http-client actor interface (will fail CI/CD since the interface isn't published yet)
- Updated tests accordingly
- Updated dependencies, namely Tokio `0.2` -> `1.1.1`

Http client 0.15

---

.github/workflows/nats-kvcache-release.yml
.github/workflows/nats-kvcache.yml
.github/workflows/nats-release.yml
README.md
fs/README.md
http-client/Cargo.toml
http-client/README.md
http-server/Cargo.toml
http-server/README.md
logging/Cargo.toml
logging/README.md
nats-kvcache/Cargo.toml
nats-kvcache/README.md
nats-kvcache/tests/integration.rs
nats/Cargo.toml
nats/README.md
nats/src/lib.rs
redis/Cargo.toml
redis/README.md
redisgraph/Cargo.toml
redisgraph/README.md
s3/Cargo.toml
s3/README.md

Apparently, our script to grab the capability contract ID does not handle comments on the same line, so I moved the NATS comment up a line.
The main feature of this PR is `crates.io` badges for the latest versions in the readme, this ensures anyone who visits this repository can automatically see the latest published crate version. I threw in a snippet about the latest OCI tag, but the OCI reference is there at least without the tag. Curious if there are suggested improvements.
I've also trawled through our READMEs and removed some lingering `wascc` references, added crates.io badges, and standardized the format of the READMEs. This will make the crates.io page look similar for all the providers and show accurate information.

Auto-updating README with crates.io versions, moved NATS comment

---

nats-kvcache/Cargo.toml
nats-kvcache/src/lib.rs
nats-kvcache/tests/integration.rs

When fixing clippy warnings in wasmcloud-host PR, decided to bump wasmcloud-host to use provider core instead of wascc-codec. This meant that I needed the NATS kvcache to use provider core ;)

Bumping NATS kvcache to provider core

---

fs/Cargo.toml
fs/src/lib.rs
s3/Cargo.toml
s3/README.md
s3/src/lib.rs
s3/src/s3.rs

Both blobstore providers (fs, s3) needed to update to the blobstore interface version `0.2.0`, mostly just to return the `BlobstoreResult` for a few operations.
While I was updating and testing the s3 provider, I added in an option to use an HTTP proxy, which is common in enterprise AWS environments. This should not affect any existing configurations as it's strictly optional.

Blobstore provider update

---

fs/Cargo.toml
fs/src/lib.rs
http-server/Cargo.toml
http-server/src/lib.rs
redisgraph/examples/sample-graph-actor/Makefile
redisgraph/examples/sample-graph-actor/README.md
redisgraph/graphdemo_manifest.yaml
redisgraph/src/lib.rs
s3/Cargo.toml
s3/src/lib.rs

Fixes #63 
With our `widl` wrapper object changes, some of the parameters for the blobstore provider functions were not the same type as the interface specifies. This PR remediates that.

Blobstore interface parity

---

telnet/Cargo.toml
telnet/README.md
telnet/src/lib.rs
telnet/src/session.rs

Fixes #32, Fixes #12 
This PR brings the `telnet` provider up to `0.15.0` standards, including making use of the `telnet` actor interface, idempotent `bind` functionality, and properly removing listeners when actors are Removed.
Speaking to the last point, I wasn't able to get the `RemoveActor` op to be delivered to this provider. Perhaps @autodidaddict can shed some light on if this should happen when I run `wash ctl stop actor`, `wash ctl stop provider`, or if it only is delivered in another case.

Brought telnet provider up to 0.15.0 standards

---

.github/workflows/TEMPLATE_provider-release.yml
.github/workflows/fs-release.yml
.github/workflows/httpclient-release.yml
.github/workflows/httpserver-release.yml
.github/workflows/logging-release.yml
.github/workflows/nats-release.yml
.github/workflows/redis-release.yml
.github/workflows/redisgraph-release.yml
.github/workflows/redisstreams-release.yml
.github/workflows/s3-release.yml
.github/workflows/telnet-release.yml
fs/Cargo.toml
http-client/Cargo.toml
http-server/Cargo.toml
logging/Cargo.toml
nats/Cargo.toml
redis-streams/Cargo.toml
redis/Cargo.toml
redisgraph/Cargo.toml
s3/Cargo.toml
telnet/Cargo.toml

This PR updates the actions for parity with the Makefile name for the compressed provider-archives and bumps each provider a patch version in order for us to re-release the provider with the `aarch64-apple-darwin` target.
This PR, once released, also fixes #72

Update actions, re-release for aarch64-apple-darwin

---

.github/workflows/TEMPLATE_provider-release.yml
.github/workflows/fs-release.yml
.github/workflows/httpclient-release.yml
.github/workflows/httpserver-release.yml
.github/workflows/logging-release.yml
.github/workflows/nats-release.yml
.github/workflows/redis-release.yml
.github/workflows/redisgraph-release.yml
.github/workflows/redisstreams-release.yml
.github/workflows/s3-release.yml
.github/workflows/telnet-release.yml
README.md

Fixes #76 
This turned out to be a release action issue, rather than Makefiles. Now, instead of sourcing the tag solely from the crate name, we will remove the `wasmcloud-` suffix.

Updated release actions to push to correct tag

---

http-server/Cargo.toml
http-server/src/lib.rs

When trying to run httpserver 0.12.2 on an M1 mac it crashes due to the use of actix_rt 2.x with actix_web 3.x.

Updated actix_web for http-server

---

build/makefiles/provider.mk

Related to a naming convention change a week ago:
wasmCloud/wash#198
Signed-off-by: Bailey Hayes <bhayes@singlestore.com>

fix: timeout and rpc-timeout changed to ms

---

httpclient/Cargo.lock
httpclient/Cargo.toml
httpserver-rs/Cargo.lock
httpserver-rs/Cargo.toml
kvredis/Cargo.lock
kvredis/Cargo.toml
lattice-controller/Cargo.lock
lattice-controller/Cargo.toml
nats/Cargo.lock
nats/Cargo.toml
sqldb-postgres/Cargo.lock
sqldb-postgres/Cargo.toml

This was a bug fix so a patch bump is acceptable and shouldn't affect any existing interfaces/actors/providers. Simply run `cargo update` to get the new version.
`v0.6.0` was yanked from crates(dot)io so developers should see a suggestion to update.

Bump providers for wasmbus-rpc-0.6.1

---

nats/README.md

From what I could tell this is the best place to put this warning. It's possible that we will want to move the invocation success/failure onto a different topic if the use case arises where listening on `wasmbus.evt.?` is desired.

Added warning about listening on wasmbus.evt

---

lattice-controller/Cargo.lock
lattice-controller/Cargo.toml
lattice-controller/src/main.rs

This PR introduces the Actor ID to the scale actor command. For now, the build will unfortunately fail as the crate is not published

Added actor ID to scale actor command

---

httpserver-rs/Cargo.lock
httpserver-rs/Cargo.toml
httpserver-rs/src/lib.rs
kv-vault/Cargo.lock
kv-vault/Cargo.toml
kvredis/Cargo.lock
kvredis/Cargo.toml
lattice-controller/Cargo.lock
lattice-controller/Cargo.toml

This PR fixes the issue found in our recent release actions that come from rmp `0.8.11`. After this merges, `lattice-controller` and `httpserver` should be published

Pin rmp serde for aarch64 linux providers

---

.github/workflows/kv-vault.yml
blobstore-s3/Cross.toml
build/makefiles/provider.mk
httpserver-rs/Cargo.lock
httpserver-rs/Cargo.toml
kv-vault/Cargo.lock
kv-vault/Cargo.toml
kv-vault/Cross.toml
kv-vault/src/client.rs
kv-vault/src/config.rs
kvredis/Cargo.lock
kvredis/Cargo.toml
lattice-controller/Cargo.lock
lattice-controller/Cargo.toml

This PR both pins `paste` to a specific version and removes intermediate `build` and `deps` artifacts between target compilations. It's still unclear as to _why_ this broke suddenly, but it's not currently worth investigating

Attempt pinning paste instead of rmp for aarch linux

---

.github/workflows/TEMPLATE_provider.yml
.github/workflows/httpclient.yml
.github/workflows/httpserver.yml
.github/workflows/kv-vault.yml
.github/workflows/kvredis.yml
.github/workflows/lattice-controller.yml
.github/workflows/nats.yml
.github/workflows/sqldb-postgres.yml

This PR changes the capability provider builds (just httpclient for easier reviews to start) to build in a matrix instead of in sequence. This cuts the release time of a provider to build+test+build provider archive down to 10ish minutes rather than the status quo of 45 minutes.
Here's a previous run: https://github.com/wasmCloud/capability-providers/actions/runs/1919866317
Here's a successful run from this PR before I re-enabled only running release on tag push: https://github.com/wasmCloud/capability-providers/actions/runs/2418640152

Run capability provider builds in parallel

---

lattice-controller/Cargo.lock
lattice-controller/Cargo.toml

Apparently `opentelemetry-otlp` pulled in libssl :( 
Signed-off-by: Connor Smith <connor@cosmonic.com>

remove dep on request from lattice controller

---

nats/Cargo.lock
nats/Cargo.toml
nats/Makefile
nats/src/main.rs
nats/tests/nats_test.rs

When there is a high volume of messages, the single async task we
spawn does not have the ability to handle the load. This handles
high throughput by spawning the actually message handling onto a
"task pool" gated by semaphores

fix(nats): Adds workpool for handling high-throughput subscriptions

---

blobstore-s3/Cargo.lock
blobstore-s3/Cargo.toml
httpclient/Cargo.lock
httpclient/Cargo.toml
httpserver-rs/Cargo.lock
httpserver-rs/Cargo.toml
httpserver-rs/tests/httpserver_test.rs
kv-vault/Cargo.lock
kv-vault/Cargo.toml
kvredis/Cargo.lock
kvredis/Cargo.toml
nats/Cargo.lock
nats/Cargo.toml
sqldb-postgres/Cargo.lock
sqldb-postgres/Cargo.toml
sqldb-postgres/src/error.rs
sqldb-postgres/src/types.rs

updated all capability providers _except_ lattice-controller, since that has work in progress in another branch.

update wasmbus-rpc to 0.10, and other dependencies

---

.github/workflows/blobstore-fs.yml
README.md
blobstore-fs/Cargo.toml
blobstore-fs/Makefile
blobstore-fs/README.md
blobstore-fs/src/fs_utils.rs
blobstore-fs/src/main.rs
blobstore-fs/tests/blobstore_fs_test.rs

This PR upgrades the blobstore-fs provider to wasmbus 0.10, adds a workflow for build/test, and updates the README to include this provider

Updated blobstore-fs to wasmbus 0.10, added workflow/readme

---

kvredis/.gitignore
kvredis/Cargo.lock
kvredis/Cargo.toml
kvredis/README.md
kvredis/src/main.rs

This PR changes the Redis connection to a ConnectionManager which automatically supervises the connection and will reconnect if Redis temporarily disconnects.
If Redis is down, users get an error message like:
```
{"error":"Host send error redis error: Reconnecting failed: Connection refused (os error 61)"}
```
Which is reasonable for the connection being down.
Edit: Smushed another change into this PR which I'm fine breaking out if desired, but I wanted to allow users to override the default URL as config_json. Default functionality is unchanged

Updated kvredis to support overridable config_json default URL and support retries

---

kvredis/Cargo.lock
kvredis/Cargo.toml
kvredis/src/main.rs

This PR ensures that:
- The kvredis provider can accept uppercase, lowercase, or initial caps `URL` values to prevent small typos
- The kvredis provider connects to 127.0.0.1 instead of 0.0.0.0 by default
Edit: apparently this only works for the `config_json` parameter... will push another commit to fix this for the linkdef parameter

Accept uppercase URL parameter, correct default connect

---

nats/Cargo.lock
nats/Cargo.toml
nats/src/main.rs

Unlike many of the other capability providers, this one didn't support the notion of supplying a single default connection configuration for all linked actors, which in turn allows actors to be linked w/out values for convenience.
None
Next release, currently planning on it being 0.15.1 as this is not a breaking change
If consumers were to accidentally leave connection data blank on link definitions, then instead of crashing this new version of the provider will attempt anonymous localhost connection to the NATS server.
Added unit test to verify that the connection configuration supplied via the start configuration doesn't need all of the fields. 
No automated acceptance tests
Added a unit test that verifies that the connection information can be …

Adding support for default connection configuration

---

blobstore-fs/Makefile
blobstore-fs/src/main.rs
build/makefiles/provider.mk

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>
This commit sanitizes the blobstore paths to resolve #200.
The primary check that is performed on the paths is ensuring that paths cannot rise *above* the given root directory.

feat: sanitize blobstore paths

---

build/makefiles/provider.mk
nats/Cargo.lock
nats/Cargo.toml
nats/src/main.rs
nats/tests/nats_test.rs

This PR addresses the issue (#196) related to NATS client subscriptions not being cleared upon drop of the individual client.
It looks like `nats.rs` does not expose the ability to close all of a clients' subscriptions, so I've added some code to manually track the subscriptions and remove them when a link is being torn down. While not strictly necessary, I've saved the subject names for subscriptions to increase usefulness of error messages.

fix: close nats provider connections on link deletion

---

nats/Cargo.lock
nats/Cargo.toml
nats/src/main.rs

Previous version would fail if the host_data.config_json was `Some("")`
n/a
n/a
Fixes a bug where 0.16.0 was basically unusable without supplying host configuration
Added unit tests to cover new rules for config ingestion
none
started host locally

Fixing the host configuration parser

---

blobstore-fs/.gitignore
blobstore-fs/Cargo.lock
blobstore-fs/Cargo.toml

Release v0.2.1 of `blobstore-fs` capability provider
N/A
`v0.2.1`
Features added since `v0.2.0` will be available, namely:
- `blobstore-fs` will no longer be able to reference file paths that are outside it's expected directory.
Run the test suite as normal
N/A
Integration tests added to suite
Verified manually during development

release(blobstore-fs): v0.2.1

---

nats/Cargo.lock
nats/Cargo.toml
nats/src/main.rs

Fixes an issue where we didn't flush after message publishes in this provider like we do during provider invocations in `wasmbus-rpc`
None
`v0.16.3`
Consumers using this provider will notice their publishes going through immediately instead of after a few (sometimes up to 40) millisecond delay
I ran through this locally with some traces to confirm that flushing improves performance.
As detailed above, I manually verified this worked. Additionally, this is the same fix that we implemented in wasmbus-rpc a few months back, so we know it works well

Ensure we flush on message publish

---

kvredis/Cargo.lock
kvredis/Cargo.toml

It looks like older versions of the `redis` crate implicitly linked to OpenSSL. The latest version of the crate supports `rustls` which we use in every other capability provider, so we should use that instead.
next

kvredis: Switch to using rustls

---

blobstore-fs/Cargo.lock
blobstore-fs/Cargo.toml
blobstore-fs/Makefile
blobstore-fs/src/main.rs
blobstore-fs/tests/blobstore_fs_test.rs

The `canonicalize` method requires that the path actually exists, which was causing problems. This uses a handy crate that does the same path cleaning as Go does. I also fixed a bunch of clippy lints we had
Blobstore FS 0.3.1
Right now this provider doesn't work, so now it will work
All tests pass and I ran through a full example using blobby
None, current tests now pass

fix(blobstore): Fixes path canonicalization

---

httpserver-rs/settings.md
httpserver-rs/src/lib.rs
httpserver-rs/src/settings.rs

The user has an option to pass cache-control into the http header as a linked value.
#238 
Next
No drastic effect. Additional and optional parameter in linkdef value.
Manual testing
NA
NA
Manually verified

Added optional cache-control to http headers

---

httpserver-rs/settings.md
httpserver-rs/src/lib.rs
httpserver-rs/src/settings.rs

The http server capability provider accepts a value on the linkef named "READONLY_MODE" that accepts boolean values. If this flag is set to true, only GET and HEAD methods are permitted.
#237 
Next
Additional feature. No significant impact on existing users.
Manual testing
NA
NA
Manually verified.

Added readonly mode to httpserver

---

httpserver-rs/Cargo.lock
httpserver-rs/Cargo.toml

Releasing https://github.com/wasmCloud/capability-providers/pull/240

Bumped httpserver to 0.18.2 for release

---

blobstore-fs/Cargo.lock
blobstore-fs/Cargo.toml
blobstore-s3/Cargo.lock
blobstore-s3/Cargo.toml
httpclient/Cargo.lock
httpclient/Cargo.toml
httpserver-rs/Cargo.lock
httpserver-rs/Cargo.toml
kv-vault/Cargo.lock
kv-vault/Cargo.toml
kvredis/Cargo.lock
kvredis/Cargo.toml
lattice-controller/Cargo.lock
lattice-controller/Cargo.toml
nats/Cargo.lock
nats/Cargo.toml
sqldb-dynamodb/Cargo.lock
sqldb-dynamodb/Cargo.toml
sqldb-postgres/Cargo.lock
sqldb-postgres/Cargo.toml

This PR bumps the version of wasmcloud-test-util to 0.10, which dropped the use of smithy-bindgen

bump wasmcloud-test-util, removing use of smithy-bindgen

---

.github/workflows/kafka.yml

Attempting to release the Kafka provider failed because the name is incorrect. This PR corrects the name.
https://github.com/wasmCloud/capability-providers/actions/runs/5803477256
kafka v0.1.0

ci(kafka): correct parcheesy name

---

blobstore-fs/Cargo.lock
blobstore-fs/Cargo.toml
blobstore-fs/src/fs_utils.rs
blobstore-fs/src/main.rs
blobstore-s3/Cargo.lock
blobstore-s3/Cargo.toml
blobstore-s3/src/lib.rs

This PR fixes two possible low severity issues in the blobstore providers. In the FS provider we're preventing infinite filesystem recursion, and in the S3 provider we're preventing an infinite loop when an actor send back invalid responses for `send_chunk`.
N/A
blobstore-fs 0.5.1
blobstore-s3 0.5.1

fix: Blobstore FS and S3 provider fixes

---

kv-vault/.gitignore
kv-vault/Cargo.lock
kv-vault/Cargo.toml
kv-vault/run-test.sh
kv-vault/src/client.rs
kv-vault/src/config.rs
kv-vault/src/main.rs
kv-vault/tests/kv_test.rs

This PR adds an async background task that attempts to renew the vault token on a predefined interval with a predefined ttl (which can be changed with configuration or linkdef parameters.)
Errors while renewing the vault token won't cause anything to error out or panic, it will just error log and retry again after the renewal period.
N/A
kv-vault 0.6.0
Added integration test that ensures that a previously generated short lived token gets renewed a couple of times.

[FEAT] Renew vault token if possible

---

README.md

This updates the README to distinguish between the stable and experimental ABIs
For a preview of the changes, see https://github.com/connorsmith256/capability-providers/tree/chore/update-readme

chore: add note about differences between stable and experimental ABIs

---

kvredis/Cargo.lock
kvredis/Cargo.toml
kvredis/src/main.rs
nats/Cargo.lock
nats/Cargo.toml
nats/src/main.rs

This PR does two things:
* adds the ability to add a custom root CA to each NATS linkdef so that you can connect to servers that might be secured with self-signed certs
* reworks how the Redis provider depends on rustls and other dependencies so that the webroot PKI certs are embedded. This removes a dependency on the host for anything TLS related.

feat: add custom CA support to the NATS provider, rework Redis TLS

---

.github/workflows/TEMPLATE_provider.yml
.github/workflows/blobstore-fs.yml
.github/workflows/blobstore-s3.yml
.github/workflows/httpclient.yml
.github/workflows/httpserver.yml
.github/workflows/kafka.yml
.github/workflows/kv-vault.yml
.github/workflows/kvredis.yml
.github/workflows/lattice-controller.yml
.github/workflows/nats.yml
.github/workflows/sqldb-postgres.yml

Signed-off-by: Brooks Townsend <brooksmtownsend@gmail.com>
This PR pins to wash 0.26 for provider archive generation as these providers are only used with pre-1.0 wasmCloud and need the capability contract ID.

ci(*): pin to 0.26 for par creation
