.github/workflows/nats-release.yml, .github/workflows/nats.yml, nats/Makefile
=> initial attempt at automated release

http-server/Cargo.toml, http-server/src/lib.rs
=> Bumping http server provider to use wasmcloud provider core

http-client/Cargo.toml, http-client/src/lib.rs
=> Update OP name and bump actor version

build/makefiles/provider.mk, kvredis/Makefile
This fixes `make` and `make test` on macos. Hopefully it doesn't cause any regressions elsewhere ;-)
=> Makefile fixes

.github/workflows/TEMPLATE_provider.yml, .github/workflows/httpclient.yml, .github/workflows/httpserver.yml, .github/workflows/kvredis.yml, .github/workflows/nats.yml, httpserver-rs/Cargo.toml, kvredis/Cargo.toml, nats/Cargo.toml, nats/Makefile, nats/provider_test_config.toml
This PR is essentially copy/filling in the other github actions for httpserver, kvredis, nats. I've added NATS for all 3, and then included redis as well for kvredis.
I've also adjusted the versions to indicate breaking changes over our current providers to avoid any possible confusion there.
=> Implement remaining actions

httpserver-rs/Cargo.lock, httpserver-rs/Cargo.toml, httpserver-rs/Makefile, httpserver-rs/provider_test_config.toml, httpserver-rs/src/lib.rs, httpserver-rs/tests/httpserver_test.rs
=> add integration test for HttpServer provider with mock actor

httpserver-rs/tests/httpserver_test.rs
=> run rustfmt

httpclient/Cargo.lock, httpclient/Cargo.toml, httpclient/src/main.rs, httpclient/tests/httpclient_test.rs, httpserver-rs/Cargo.lock, httpserver-rs/Cargo.toml, httpserver-rs/bin/main.rs, kvredis/Cargo.lock, kvredis/Cargo.toml, kvredis/src/main.rs, nats/Cargo.toml, nats/src/main.rs
Use derive macro in providers.
new versions:
httpclient: 0.3.1
httpserver: 0.14.2
kvredis: 0.14.1
nats: 0.11.1
=> Derive macro provider dispatch

httpserver-rs/Cargo.lock, httpserver-rs/Cargo.toml, httpserver-rs/src/lib.rs, httpserver-rs/src/settings.rs
=> bump wasmbus-rpc to 0.3.12, bump crate to 0.14.3

build/makefiles/provider.mk
=> add rules to print target files

build/makefiles/provider.mk
=> move new rules lower so they don't override default rule

.github/workflows/sqldb-postgres.yml, sqldb-postgres/Cross.toml
- add Cross.toml to sqldb-postgres
- update workflow (for sqldb-postgres) to enable manual workflow trigger (for occasions like this when it's already tagged)
=> Sqldb cross workflow

.github/workflows/nats.yml
We use a different name for that nats binary and this edits the
pipeline to take this into account
=> fix(actions): Makes sure the right binary/project name is used

.github/CODEOWNERS
=> add stevelr to codeowners

build/makefiles/provider.mk
=> Scripted first par target, allow configuration

lattice-controller/Cargo.lock, lattice-controller/Cargo.toml, lattice-controller/Makefile, lattice-controller/src/main.rs
Signed-off-by: Kevin Hoffman <autodidaddict@users.noreply.github.com>
=> Allows for a global fallback configuration used for all bound actors

.github/workflows/lattice-controller.yml
=> Changed lattice controller subject key to secret

lattice-controller/Cargo.toml, lattice-controller/Makefile, lattice-controller/provider_test_config.toml
Signed-off-by: Kevin Hoffman <autodidaddict@users.noreply.github.com>
=> moar CI attempts

lattice-controller/Cargo.lock, lattice-controller/Cargo.toml, lattice-controller/src/main.rs
Signed-off-by: Connor Smith <connor@cosmonic.com>
=> add ScaleActorCommand to lattice controller

lattice-controller/Cargo.lock, lattice-controller/Cargo.toml, lattice-controller/src/main.rs
=> migrate from nats asynk to aflowt

lattice-controller/Cargo.lock, lattice-controller/Cargo.toml
=> Enabled starting providers without specifying a host ID

nats/tests/nats_test.rs
=> fix anats import path

httpclient/Makefile, httpserver-rs/Cargo.lock, httpserver-rs/Cargo.toml, httpserver-rs/Makefile, kvredis/Cargo.lock, kvredis/Cargo.toml, kvredis/Makefile, lattice-controller/Cargo.lock, lattice-controller/Cargo.toml, lattice-controller/Makefile, nats/Cargo.lock, nats/Cargo.toml, nats/Makefile, sqldb-postgres/Cargo.lock, sqldb-postgres/Cargo.toml, sqldb-postgres/Makefile
=> Ensured all capability providers have friendly names

lattice-controller/Cargo.lock, lattice-controller/Cargo.toml, lattice-controller/src/main.rs
Signed-off-by: Kevin Hoffman <autodidaddict@users.noreply.github.com>
=> Adding support for putting registry credential maps

sqldb-postgres/Cargo.lock, sqldb-postgres/Cargo.toml, sqldb-postgres/src/config.rs, sqldb-postgres/src/main.rs, sqldb-postgres/src/types.rs, sqldb-postgres/tests/queries.rs
=> update dependencies; use latest sqldb interface

Makefile, blobstore-s3/Cargo.lock, blobstore-s3/Cargo.toml, blobstore-s3/Makefile, blobstore-s3/README.md, blobstore-s3/codegen.toml, blobstore-s3/provider_test_config.toml, blobstore-s3/src/config.rs, blobstore-s3/src/lib.rs, blobstore-s3/src/main.rs, blobstore-s3/tests/large_data.rs, httpclient/tests/httpclient_test.rs, kv-vault/src/client.rs, kv-vault/tests/kv_test.rs, kvredis/tests/kv_test.rs, lattice-controller/tests/lattice_controller_test.rs
restoring stuff that got missed in last merge
=> Wasmbus rpc 0.8.2 finish

httpserver-rs/Cargo.lock, httpserver-rs/Cargo.toml
=> updated rmp to fix httpserver glibc issue

sqldb-postgres/Cargo.lock, sqldb-postgres/Cargo.toml
This version has tracing
Signed-off-by: Connor Smith <connor@cosmonic.com>
=> bump version of sqldb-postgres provider

lattice-controller/Cargo.lock, lattice-controller/Cargo.toml
Signed-off-by: Kevin Hoffman <autodidaddict@users.noreply.github.com>
=> Updating to latest version of control interface

.github/workflows/blobstore-s3.yml
workflow for testing/building/releasing blobstore-s3 capability provider.
Needs `secrets.WASMCLOUD_BLOBSTORE_S3` added to gitub before it will run
=> add blobstore-s3 workflow

.github/workflows/blobstore-s3.yml, .github/workflows/kv-vault.yml, blobstore-s3/Cargo.lock, blobstore-s3/Cargo.toml, blobstore-s3/Makefile, blobstore-s3/README.md, blobstore-s3/src/config.rs, blobstore-s3/src/lib.rs, blobstore-s3/tests/large_data.rs, blobstore-s3/tests/storage.rs, kv-vault/Cargo.toml
=> Corrected build failures and artifact names for blobstore/kvvault

.github/workflows/kv-vault.yml
Fixed it in one place but not the other 😢
=> Corrected binary name for kv-vault in assemble step

.github/workflows/blobstore-s3.yml, .github/workflows/httpserver.yml
This PR refactors the blobstore CI to run in parallel like the others for efficiency
=> Refactored blobstore-s3 ci to build in parallel

sqldb-postgres/Cargo.lock, sqldb-postgres/Cargo.toml, sqldb-postgres/Makefile
=> sqldb-postgres Makefile should use version from Cargo.toml

nats/Cargo.lock, nats/Cargo.toml, nats/src/main.rs
Signed-off-by: Connor Smith <connor@cosmonic.com>
=> include OTEL header on NATS requests

blobstore-fs/Cross.toml
=> added Cross.toml for blobstore fs

.github/workflows/blobstore-fs.yml, blobstore-fs/Cargo.toml, blobstore-fs/Makefile, blobstore-fs/src/main.rs
This PR:
1. Corrects the par artifact name
2. Changes the `log` crate to `tracing`
3. Changes a `std::fs::write` command that created an empty file to `File::create`, fixing a bug
@matsbror feel free to chime in here if there's anything of note 😄
=> Blobstore FS create object fix, updated logs

.github/workflows/TEMPLATE_provider.yml, .github/workflows/blobstore-fs.yml, .github/workflows/blobstore-s3.yml, .github/workflows/httpclient.yml, .github/workflows/httpserver.yml, .github/workflows/kv-vault.yml, .github/workflows/kvredis.yml, .github/workflows/lattice-controller.yml, .github/workflows/nats.yml, .github/workflows/sqldb-postgres.yml
=> pinned CI to ubuntu 20.04 for compatibility

.github/workflows/blobstore-s3.yml
This should resolve #201 (see https://github.com/wasmCloud/weld/pull/141)
=> fix(ci): set XDG_CACHE_HOME explicitly for native build

nats/Cargo.lock, nats/Cargo.toml, nats/src/main.rs
When the topic being used is `$SYS.REQ.CLAIMS.UPDATE` (and possibly a few others), the NATS server (currently 2.9.3) will fail to parse the claims update because it's attempting to parse the header instead.
n/a
nats-v0.16.2
Super small edge case that will only pop up if people are using this provider to perform NATS server/system maintenance
re-ran test from Makefile
No new unit tests added
Pending
=> Blocks use of headers on SYS topics

httpserver-rs/Cargo.lock, httpserver-rs/Cargo.toml
This makes the dependency graph smaller and simplifies cross-compilation. Note, that this is already used for `httpclient` https://github.com/wasmCloud/capability-providers/blob/315a1db75c302c1f68b1d68e95994489636bebb0/httpclient/Cargo.toml#L15
=> build(httpserver-rs): use `rustls` for TLS in tests

kvredis/Cargo.lock, nats/Cargo.lock, nats/Cargo.toml
=> Bumpity bump

blobstore-fs/Cargo.lock, blobstore-fs/Cargo.toml, blobstore-s3/Cargo.lock, blobstore-s3/Cargo.toml, httpclient/Cargo.lock, httpclient/Cargo.toml, httpserver-rs/Cargo.lock, httpserver-rs/Cargo.toml, kv-vault/Cargo.lock, kv-vault/Cargo.toml, kvredis/Cargo.lock, kvredis/Cargo.toml, lattice-controller/Cargo.lock, lattice-controller/Cargo.toml, nats/Cargo.lock, nats/Cargo.toml, sqldb-postgres/Cargo.lock, sqldb-postgres/Cargo.toml
Add a few file size optimization options to each provider's release build so that we get much smaller binaries.
=> Add file optmization options to release builds

nats/Cargo.lock, nats/Cargo.toml
Draft until the interface is released
=> chore(nats): bump wasmbus-rpc 0.14 and async-nats 0.30

httpclient/Cargo.lock, httpclient/Cargo.toml
update httpclient to wasmbus-rpc@0.14.0 and wasmcloud-interface-httpclient@0.10
=> update httpclient to wasmbus-rpc@0.14.0 and wasmcloud-interface-httpclient@0.10

httpserver-rs/Cargo.lock, httpserver-rs/Cargo.toml
update httpserver-rs to use wasmbus-rpc@0.14
=> update httpserver-rs to use wasmbus-rpc@0.14

blobstore-fs/Cargo.lock, blobstore-fs/Cargo.toml
=> bump wasmbus-rpc

kv-vault/Cargo.lock, kv-vault/Cargo.toml, kv-vault/run-test.sh
Use the latest  version of wasmbus-rpc
=> Update kv-vault to use wasmbus-rpc 0.14

README.md
=> adding examples for pulling the latest docs

.github/workflows/TEMPLATE_provider.yml, .github/workflows/blobstore-fs.yml, .github/workflows/blobstore-s3.yml, .github/workflows/httpclient.yml, .github/workflows/httpserver-lib.yml, .github/workflows/httpserver.yml, .github/workflows/kafka.yml, .github/workflows/kv-vault.yml, .github/workflows/kvredis.yml, .github/workflows/lattice-controller.yml, .github/workflows/nats.yml, .github/workflows/sqldb-postgres.yml
=> ci: update actions
